# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]

env:
  DEPLOY_VER: 0a7f19d38d7fe8c13587e2b02f0c8bca4accfcb51f2921285dac1616090c7abd
  YEAR: 2020

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
       
        run: |
          ls
          cat log.txt
          echo 'Hello from  ${{ env.DEPLOY_VER }}'
  job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env: # Or as an environment variable
        FAVORITE_DAY_OF_WEEK: ${{ secrets.FAVORITE_DAY_OF_WEEK }}
        MONTH: May
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env: # Or as an environment variable
          DAY_OF_THE_MONTH: 23

        run: |
          date
          echo 'Day - $DAY_OF_THE_MONTH'
          echo 'Month - ${{ env.MONTH }} '
          echo 'Year - ${{ env.YEAR }} '
          echo 'My favorite day of week is - $FAVORITE_DAY_OF_WEEK '
